server:
  servlet:
    context-path: /api-list
    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api-list?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: nys123456
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  freemarker:
    suffix: .ftl
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    redis:
      repositories:
        enabled: false
api: 
  count: 5
